services:
  - type: web
    name: egx-advisor-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: APP_ENV
        value: production

  - type: web
    name: egx-advisor-ui
    runtime: docker
    dockerfilePath: ./Dockerfile.streamlit
    plan: free
    healthCheckPath: /_stcore/health
    envVars:
      - key: BACKEND_URL
        sync: false